title: igarash1
google_analytics:

header_pages:
  - index.md
  - about.md
  - contact.md

footer: 
  '<a href="https://github.com/igarash1/igarash1.github.io">source</a>'

style: light

plugins:
  - jekyll-seo-tag
  - jekyll-responsive-image

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

responsive_image:
  template: _includes/responsive-image.html
  