title: igarash1
google_analytics:

header_pages:
  - index.md
  - about.md
  - '<a href="https://github.com/igarash1">github</a>'
  - '<a href="https://twitter.com/igarash1">twitter</a>'


footer: 
  - '<a href="mailto:igarashi.kouki@gmail.com">contact</a>'
  - '<a href="https://github.com/igarash1/igarash1.github.io">source</a>'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
