title: igarash1
google_analytics:

header_pages:
  - index.md
  - about.md
  - page: github
    url:  https://github.com/igarash1
  - page: twitter
    url:  https://twitter.com/igarash1

footer: 
  '<a href="mailto:igarashi.kouki@gmail.com">contact</a> /<a href="https://github.com/igarash1/igarash1.github.io">source</a>'

style: light

plugins:
- jekyll-seo-tag

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
