title: igarash1
google_analytics:

header_pages:
  - index.md
  - about.md
  - contact.md

footer: 
  '<a href="https://github.com/igarash1/igarash1.github.io">source</a>'

style: light

plugins:
  - jekyll-seo-tag
  - jekyll-responsive-image

markdown: redcarpet
remote_theme: b2a3e8/jekyll-theme-console

picture:
  source: assets/images/_fullsize
  output: generated
  markup: picture
  presets:
      # Full width own setting for jekyll standard template pictures
    jekyll:
      ppi: [1, 1.5]
      attr:
        class: jekyll
        itemprop: image
      source_lrg:
        media: "(min-width: 50em)"
        width: 800
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
